<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="com.bbagym.model.vo.Member"%>

<%
	Member logginMember = (Member) session.getAttribute("logginMember");

	Cookie[] cookies = request.getCookies();
	String saveId = "";
	if (cookies != null) {
		for (Cookie c : cookies) {
			if (c.getName().equals("saveId")) {
			
				saveId = c.getValue();
			}
		}
	}
%>

<script src="<%=request.getContextPath()%>/js/jquery-3.4.1.min.js"></script>

<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/style.css">

<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>

<div class="page-header page-header-xs" data-parallax="true"
	style="background-image: url('<%=request.getContextPath()%>/assets/img/fabio-mangione.jpg');"></div>
<div class="container pt-3 center-info ">
	<link rel="stylesheet" href="css/member-register.css">



	<div class="row">
		<div class="col-lg-8 col-md-8 col-sm-12">
			<h1 class="mt-4" style="text-align: center;"></h1>
			<br>
			<h3 style="text-align: center;"></h3>

			<div>
				<!-- 		<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> -->


				
					<div style="width: 50%; padding-top: 250px">
					<div style="text-align: center;color:gray;">
					<div style="color:black;">
						닉네임 <h1 class="style">♥&nbsp&nbsp   <%=logginMember.getM_NAME() %>   &nbsp&nbsp♥ </h1>회원님
						<br> <h4>새 비밀번호를 입력해주세요.</h4></div><br>
						<br>


						<form name="" action="<%=request.getContextPath()%>/member/PasswordEnd"
							method="post">
							<input type="hidden" name="password" id="password"
										value="<%=logginMember.getM_PW()%>" readonly>
											</h4><th>변경할 비밀번호</th>
									<td><input  style="height:30px;"type="password" name="password_new"
										id="password_new" required></td>
							<br>
									<br><th>비밀번호 확인&nbsp&nbsp&nbsp&nbsp</th>
									<input  style="height:30px;" type="password" id="password_chk" required><br>
									
								
								<br>
								<input id="style"type="submit"
										onclick="return password_validate();" value="변경" />&nbsp; 
										
								<style>
								#style{
								color:black;
									width:70px;
									height:30px;
								}
								#style:hover{
									background-color:pink;
								}
								.style{
								
								-webkit-animation: tracking-in-contract-bck 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-contract-bck 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        }
	        /* ----------------------------------------------
 * Generated by Animista on 2020-4-15 11:8:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract-bck
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-contract-bck {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px);
            transform: translateZ(400px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes tracking-in-contract-bck {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px);
            transform: translateZ(400px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
	        
								</style>
							
							<input type="hidden" name="M_ID"
								value="<%=logginMember.getM_ID()%>" />
						</form>
				
					<script>
		function password_validate(){
			var pw=document.querySelector("#password_new").value;
			var pwck=document.querySelector("#password_chk").value;
			if(pw!=pwck){
				alert("새 패스워드가 일치하지 않습니다.");
				return false;
			}
			return true;
		}
	</script>
						</div>
		
						</div>


					</div>
				<br>											
				<button type="button"class="submit" onclick="location.replace('<%=request.getContextPath()%>/member/logoutgologin.do')">로그인페이지로 이동</button>
				<br><button type="button"class="submit" onclick="location.replace('<%=request.getContextPath()%>/member/logout.do')">메인 화면으로 돌아가기</button>
				
				<br>
			</div>
			


		</div>










		<br> <br> <br> <br>
		<br> <br>


		<style>
* {
	margin: 0;
	padding: 0;
	font-family: sans-serif;
	/* border: 1px solid rgb(211, 208, 208); */
}

.togglebtn {
	padding: 10px 30px;
	cursor: pointer;
	background: transparent;
	border: 0;
	outline: none;
	position: relative;
}

#btn {
	top: 0;
	left: 0;
	position: absolute;
	width: 110px;
	height: 100%;
	background: linear-gradient(to right, #fffff6, rgb(255, 199, 199));
	border-radius: 30px;
	transition: .5s;
}

.input-group {
	top: 90px;
	position: absolute;
	width: 280px;
	transition: .5s;
}

.input-field {
	width: 100%;
	padding: 10px 0;
	margin: 5px 0;
	border: none;
	border-bottom: 1px solid #999;
	outline: none;
	background: transparent;
}

.submit {
	width: 85%;
	padding: 10px 30px;
	padding-left: 40px;
	cursor: pointer;
	display: block;
	margin: auto;
	background: linear-gradient(to right, #fffff6, rgb(255, 199, 199));
	border: 0;
	outline: none;
	border-radius: 30px;
}

.find {
	width: 85%;
	padding: 10px 30px;
	cursor: pointer;
	display: block;
	margin: auto;
	background: linear-gradient(to right, #fffff6, rgb(255, 199, 199));
	border: 0;
	outline: none;
	border-radius: 30px;
}

.kakao {
	padding: 10px 30px;
	cursor: pointer;
	display: block;
	margin: auto;
	border: 0;
	outline: none;
	border-radius: 30px;
}

.checkbox {
	margin: 30px 10px 30px 0;
}

span {
	color: #777;
	font-size: 12px;
	bottom: 126px; /*68px*/
	position: absolute;
}

#login {
	left: 50px;
}
</style>
		<%@ include file="/views/common/footer.jsp"%>